transcoding: new design proposal

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -38,9 +38,9 @@ OPTIONS=(
   "libx264_static:yes"
   "libx265:no"
   "libx265_static:yes"
-  "vdpau:auto"
-  "libmfx:no"
-  "libmfx_static:yes"
+  "qsv:no"
+  "vaapi:no"
+  "vdpau:no"
   "inotify:auto"
   "epoll:auto"
   "uriparser:auto"
@@ -138,7 +138,7 @@ else
   COMPILER=gcc
 fi
 
-check_cc_snippet getloadavg '#include <stdlib.h> 
+check_cc_snippet getloadavg '#include <stdlib.h>
 void test() { getloadavg(NULL,0); }'
 
 check_cc_snippet atomic64 '#include <stdint.h>
@@ -385,7 +385,7 @@ if enabled libffmpeg_static; then
 
   # libx264
   if disabled libx264_static; then
-    check_cc_lib x264 || die "libx264 not found"
+    check_pkg x264 ">=0.142" || die "libx264 not found"
   fi
 
   # libx265
@@ -395,43 +395,28 @@ if enabled libffmpeg_static; then
       check_cc_lib stdc++ stdcpp ||\
         die "libstdc++ not found (needed for building libx265)"
     else
-      check_cc_lib x265 || die "libx265 not found"
+      check_pkg x265 ">=1.7" || die "libx265 not found"
     fi
   else
     disable libx265_static
   fi
 
-  # vdpau
-  if enabled_or_auto vdpau; then
-    if check_pkg vdpau; then
-      enable vdpau
-    elif enabled vdpau; then
-      die "vdpau (Video API library) not found"
-    fi
+  # qsv
+  if enabled qsv; then
+    enable experimental
+    enable hwaccels
   fi
 
-  # libmfx
-  if enabled libmfx; then
-    check_cc_lib va || die "libva not found"
-    check_cc_lib va-drm va_drm || disable va_drm
-    check_cc_lib va-x11 va_x11 || disable va_x11
-    if disabled va_drm && disabled va_x11; then
-      die "neither libva-drm nor libva-x11 was found"
-    fi
-    if enabled libmfx_static; then
-      check_bin autoreconf ||\
-        die "autoreconf not found (needed for building libmfx)"
-      check_bin libtool ||\
-        die "libtool not found (needed for building libmfx)"
-      check_bin libtoolize ||\
-        die "libtoolize not found (needed for building libmfx)"
-      check_cc_lib stdc++ stdcpp ||\
-        die "libstdc++ not found (needed for building libmfx)"
-    else
-      check_cc_lib mfx || die "libmfx not found"
-    fi
-  else
-    disable libmfx_static
+  # vaapi
+  if enabled vaapi; then
+    enable experimental
+    enable hwaccels
+  fi
+
+  # vdpau
+  if enabled vdpau; then
+    enable experimental
+    enable hwaccels
   fi
 
 else
